/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/0wT4GCjbyZQsHpef/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#000000"]} />
      <group {...props} dispose={null}>
        <directionalLight
          name="Directional Light 2"
          intensity={2.39}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#fe00e9"
          position={[-1054.45, 1051.32, -654.47]}
        />
        <group name="Monitor" position={[62, 808.37, -253.72]} scale={1.14}>
          <group name="Row 6" position={[-0.87, -290.35, 14.04]}>
            <group name="Key 5" position={[177.13, 0, 0]}>
              <group name="Text" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="0"
                  geometry={nodes["0"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 4" position={[90.81, 0, 0]}>
              <group name="Text1" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="01"
                  geometry={nodes["01"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 3" position={[3.5, 0, 0]}>
              <group name="Text2" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="02"
                  geometry={nodes["02"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 2" position={[-86.13, 0, 0]}>
              <group name="Text3" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="03"
                  geometry={nodes["03"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube3"
                geometry={nodes.Cube3.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key" position={[-177.13, 0, 0]}>
              <group name="Text4" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="04"
                  geometry={nodes["04"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube4"
                geometry={nodes.Cube4.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <group name="Row 5" position={[-0.87, -171.67, 14.04]}>
            <group name="Key 51" position={[177.13, 0, 0]}>
              <group name="Text5" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="05"
                  geometry={nodes["05"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube5"
                geometry={nodes.Cube5.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 41" position={[90.81, 0, 0]}>
              <group name="Text6" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="06"
                  geometry={nodes["06"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube6"
                geometry={nodes.Cube6.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 31" position={[3.5, 0, 0]}>
              <group name="Text7" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="07"
                  geometry={nodes["07"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube7"
                geometry={nodes.Cube7.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 21" position={[-86.13, 0, 0]}>
              <group name="Text8" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="08"
                  geometry={nodes["08"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube8"
                geometry={nodes.Cube8.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key1" position={[-177.13, 0, 0]}>
              <group name="Text9" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="09"
                  geometry={nodes["09"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube9"
                geometry={nodes.Cube9.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <group name="Row 4" position={[-0.87, -51.76, 14.04]}>
            <group name="Key 52" position={[177.13, 0, 0]}>
              <group name="Text10" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="010"
                  geometry={nodes["010"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube10"
                geometry={nodes.Cube10.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 42" position={[90.81, 0, 0]}>
              <group name="Text11" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="011"
                  geometry={nodes["011"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube11"
                geometry={nodes.Cube11.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 32" position={[3.5, 0, 0]}>
              <group name="Text12" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="012"
                  geometry={nodes["012"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube12"
                geometry={nodes.Cube12.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 22" position={[-86.13, 0, 0]}>
              <group name="Text13" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="013"
                  geometry={nodes["013"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube13"
                geometry={nodes.Cube13.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key2" position={[-177.13, 0, 0]}>
              <group name="Text14" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="014"
                  geometry={nodes["014"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube14"
                geometry={nodes.Cube14.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <group name="Row 3" position={[-0.87, 68.05, 14.04]}>
            <group name="Key 53" position={[177.13, 0, 0]}>
              <group name="Text15" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="015"
                  geometry={nodes["015"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube15"
                geometry={nodes.Cube15.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 43" position={[90.81, 0, 0]}>
              <group name="Text16" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="016"
                  geometry={nodes["016"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube16"
                geometry={nodes.Cube16.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 33" position={[3.5, 0, 0]}>
              <group name="Text17" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="017"
                  geometry={nodes["017"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube17"
                geometry={nodes.Cube17.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 23" position={[-86.13, 0, 0]}>
              <group name="Text18" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="018"
                  geometry={nodes["018"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube18"
                geometry={nodes.Cube18.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key3" position={[-177.13, 0, 0]}>
              <group name="Text19" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="019"
                  geometry={nodes["019"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube19"
                geometry={nodes.Cube19.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <group name="Row 2" position={[-0.87, 185.78, 9.28]}>
            <group name="Key 54" position={[177.13, 0, 0]}>
              <group name="Text20" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="020"
                  geometry={nodes["020"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube20"
                geometry={nodes.Cube20.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 44" position={[90.81, 0, 0]}>
              <group name="Text21" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="021"
                  geometry={nodes["021"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube21"
                geometry={nodes.Cube21.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 34" position={[3.5, 0, 0]}>
              <group name="Text22" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="022"
                  geometry={nodes["022"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube22"
                geometry={nodes.Cube22.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 24" position={[-86.13, 0, 0]}>
              <group name="Text23" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="023"
                  geometry={nodes["023"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube23"
                geometry={nodes.Cube23.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key4" position={[-177.13, 0, 0]}>
              <group name="Text24" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="024"
                  geometry={nodes["024"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube24"
                geometry={nodes.Cube24.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <group name="Row" position={[-0.87, 299.12, 14.04]}>
            <group name="Key 55" position={[177.13, 0, 0]}>
              <group name="Text25" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="025"
                  geometry={nodes["025"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube25"
                geometry={nodes.Cube25.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 45" position={[90.81, 0, 0]}>
              <group name="Text26" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="026"
                  geometry={nodes["026"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube26"
                geometry={nodes.Cube26.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 35" position={[3.5, 0, 0]}>
              <group name="Text27" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="027"
                  geometry={nodes["027"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube27"
                geometry={nodes.Cube27.geometry}
                material={materials.Yellow}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key 25" position={[-86.13, 0, 0]}>
              <group name="Text28" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="028"
                  geometry={nodes["028"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube28"
                geometry={nodes.Cube28.geometry}
                material={materials.Green}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
            <group name="Key5" position={[-177.13, 0, 0]}>
              <group name="Text29" position={[3.57, 4.6, 16.68]}>
                <mesh
                  name="029"
                  geometry={nodes["029"].geometry}
                  material={materials["My Text Material"]}
                  castShadow
                  receiveShadow
                  position={[-11.71, -14.13, 0]}
                />
              </group>
              <mesh
                name="Cube29"
                geometry={nodes.Cube29.geometry}
                material={materials.Grey}
                castShadow
                receiveShadow
                position={[0, 0, -5.45]}
                scale={1.12}
              />
            </group>
          </group>
          <mesh
            name="Screen"
            geometry={nodes.Screen.geometry}
            material={materials["Device-screen"]}
            castShadow
            receiveShadow
            position={[0, -0.38, 10.72]}
            scale={[1.08, 1.05, 1.03]}
          />
          <mesh
            name="Device"
            geometry={nodes.Device.geometry}
            material={materials["Device Material"]}
            castShadow
            receiveShadow
            position={[0, 0, -30.72]}
            scale={[1.05, 1.16, 1]}
          />
        </group>
        <group name="Keyboard" rotation={[1.12, 0, 0]}>
          <group
            name="Board"
            position={[0, -57.36, 0]}
            scale={[0.57, 0.57, 0.6]}>
            <mesh
              name="Rectangle 2"
              geometry={nodes["Rectangle 2"].geometry}
              material={materials["Rectangle 2 Material"]}
              castShadow
              receiveShadow
              position={[0, -36.67, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.06, 1.13, 1.03]}
            />
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials["Rectangle Material"]}
              castShadow
              receiveShadow
              position={[0, -11.33, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.02, 1, 1]}
            />
          </group>
          <group name="Enter" position={[382.6, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text30"
              position={[34.32, 104.5, 20.73]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="G"
                geometry={nodes.G.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-63, 9, 0]}
              />
              <mesh
                name="O"
                geometry={nodes.O.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-32.7, 9, 0]}
              />
            </group>
            <mesh
              name="Cube30"
              geometry={nodes.Cube30.geometry}
              material={materials["Key-yellow"]}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-P" position={[566.4, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-P"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="P"
                geometry={nodes.P.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-P"
              geometry={nodes["Cube-P"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-K" position={[342.04, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-K"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="K"
                geometry={nodes.K.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-K"
              geometry={nodes["Cube-K"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-I" position={[312.13, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-I"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="I"
                geometry={nodes.I.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-I"
              geometry={nodes["Cube-I"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-V" position={[-117.91, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-V"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="V"
                geometry={nodes.V.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-V"
              geometry={nodes["Cube-V"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-F" position={[-157.91, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-F"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="F"
                geometry={nodes.F.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-F"
              geometry={nodes["Cube-F"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-R" position={[-187.82, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-R"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="R"
                geometry={nodes.R.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-R"
              geometry={nodes["Cube-R"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-N" position={[133.51, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-N"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="N"
                geometry={nodes.N.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-N"
              geometry={nodes["Cube-N"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-H" position={[93.51, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-H"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="H"
                geometry={nodes.H.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-H"
              geometry={nodes["Cube-H"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-Y" position={[63.6, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-Y"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="Y"
                geometry={nodes.Y.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-Y"
              geometry={nodes["Cube-Y"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-X" position={[-366.44, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-X"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="X"
                geometry={nodes.X.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-X"
              geometry={nodes["Cube-X"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-S" position={[-406.44, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-S"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="S"
                geometry={nodes.S.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-S"
              geometry={nodes["Cube-S"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-W" position={[-436.35, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-W"
              position={[7.83, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="W"
                geometry={nodes.W.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-W"
              geometry={nodes["Cube-W"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-L" position={[472.08, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-L"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="L"
                geometry={nodes.L.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-L"
              geometry={nodes["Cube-L"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-O" position={[442.17, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-O"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="O1"
                geometry={nodes.O1.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-O"
              geometry={nodes["Cube-O"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-M" position={[257.81, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-M"
              position={[-1.66, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="M"
                geometry={nodes.M.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-M"
              geometry={nodes["Cube-M"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-J" position={[217.81, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-J"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="J"
                geometry={nodes.J.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-J"
              geometry={nodes["Cube-J"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-U" position={[187.9, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-U"
              position={[18.2, 104.5, -10.58]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="U"
                geometry={nodes.U.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-U"
              geometry={nodes["Cube-U"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-C" position={[-242.14, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-C"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="C"
                geometry={nodes.C.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-C"
              geometry={nodes["Cube-C"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-D" position={[-282.14, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-D"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="D"
                geometry={nodes.D.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-D"
              geometry={nodes["Cube-D"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-E" position={[-312.05, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text -E"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="E"
                geometry={nodes.E.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-E"
              geometry={nodes["Cube-E"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-B" position={[9.28, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text-B"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="B"
                geometry={nodes.B.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-B"
              geometry={nodes["Cube-B"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-G" position={[-30.72, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-G"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="G1"
                geometry={nodes.G1.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-G"
              geometry={nodes["Cube-G"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-T" position={[-60.63, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-T"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="T"
                geometry={nodes.T.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-T"
              geometry={nodes["Cube-T"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-Z" position={[-490.67, 20.49, 126.15]} scale={0.55}>
            <group
              name="Text -Z"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="Z"
                geometry={nodes.Z.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-Z"
              geometry={nodes["Cube-Z"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-A" position={[-530.67, 20.49, -0.47]} scale={0.55}>
            <group
              name="Text-A"
              position={[17.75, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="A"
                geometry={nodes.A.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube-A"
              geometry={nodes["Cube-A"].geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
          <group name="Key-Q" position={[-560.58, 20.49, -126.28]} scale={0.55}>
            <group
              name="Text-Q"
              position={[9.95, 104.5, -10.55]}
              rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                name="Q"
                geometry={nodes.Q.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-27.91, -26.97, 0]}
              />
            </group>
            <mesh
              name="Cube31"
              geometry={nodes.Cube31.geometry}
              material={materials.Key}
              castShadow
              receiveShadow
              position={[0, -0.5, 0]}
            />
          </group>
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.5}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#ae00fe"
          position={[1275.86, 1533.49, 1492.42]}
          rotation={[-0.22, 0, 0]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.44}
          far={100000}
          near={-100000}
          position={[-299.88, 384.83, 1206.25]}
          rotation={[0.12, -0.3, 0.04]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.6}
          color="#eaeaea"
          position={[0, 1, 0]}
        />
      </group>
    </>
  );
}
